from __future__ import annotations
from typing import Protocol
from app.domain.models import TaskEvent, TaskRecord

class TaskRepository(Protocol):
    def save_task(self, rec: TaskRecord) -> None: ...
    def update_task(self, rec: TaskRecord) -> None: ...
    def get_task(self, task_id: str) -> TaskRecord | None: ...
    def list_tasks(self, limit: int = 100, state: str | None = None) -> list[TaskRecord]: ...
    def append_event(self, task_id: str, event: TaskEvent) -> None: ...
    def list_events(self, task_id: str) -> list[TaskEvent]: ...
    def health_check(self) -> bool: ...
